In [3]:
pip install tensorflow --ignore-installed

Defaulting to user installation because normal site-packages is not writeable
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
  Using cached oauthlib-3.2.1-py3-none-any.whl (151 kB)
  Using cached MarkupSafe-2.1.1-cp39-cp39-win_amd64.whl (17 kB)
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Note: you may need to 

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account al

In [4]:
# Artificial Neural Network

# Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.10.0'

In [6]:
# Part 1 - Data Preprocessing

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [7]:
# Encoding categorical data
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
# Part 2 - Building the ANN

# Initializing the ANN
ann = tf.keras.models.Sequential()

In [11]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [12]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [13]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [14]:
# Part 3 - Training the ANN

# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [15]:
# Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 875us/step - loss: 0.5169 - accuracy: 0.7947
Epoch 2/100
250/250 [==============================] - 0s 803us/step - loss: 0.4576 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 791us/step - loss: 0.4383 - accuracy: 0.7972
Epoch 4/100
250/250 [==============================] - 0s 811us/step - loss: 0.4252 - accuracy: 0.8021
Epoch 5/100
250/250 [==============================] - 0s 803us/step - loss: 0.4133 - accuracy: 0.8060
Epoch 6/100
250/250 [==============================] - 0s 779us/step - loss: 0.4005 - accuracy: 0.8106
Epoch 7/100
250/250 [==============================] - 0s 799us/step - loss: 0.3900 - accuracy: 0.8160
Epoch 8/100
250/250 [==============================] - 0s 839us/step - loss: 0.3816 - accuracy: 0.8196
Epoch 9/100
250/250 [==============================] - 0s 859us/step - loss: 0.3750 - accuracy: 0.8436
Epoch 10/100
250/250 [==============================] - 0s 823us/step - l

250/250 [==============================] - 0s 807us/step - loss: 0.3338 - accuracy: 0.8640
Epoch 80/100
250/250 [==============================] - 0s 831us/step - loss: 0.3338 - accuracy: 0.8622
Epoch 81/100
250/250 [==============================] - 0s 783us/step - loss: 0.3340 - accuracy: 0.8630
Epoch 82/100
250/250 [==============================] - 0s 779us/step - loss: 0.3337 - accuracy: 0.8641
Epoch 83/100
250/250 [==============================] - 0s 791us/step - loss: 0.3337 - accuracy: 0.8652
Epoch 84/100
250/250 [==============================] - 0s 779us/step - loss: 0.3338 - accuracy: 0.8643
Epoch 85/100
250/250 [==============================] - 0s 779us/step - loss: 0.3336 - accuracy: 0.8635
Epoch 86/100
250/250 [==============================] - 0s 775us/step - loss: 0.3337 - accuracy: 0.8620
Epoch 87/100
250/250 [==============================] - 0s 779us/step - loss: 0.3333 - accuracy: 0.8625
Epoch 88/100
250/250 [==============================] - 0s 783us/step - loss:

In [16]:
# Part 4 - Making the predictions and evaluating the model

# Predicting the result of a single observation

"""
Using this ANN model to predict if the customer with the following informations will leave the bank: 
Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: $ 60000
Number of Products: 2
Does this customer have a credit card? Yes
Is this customer an Active Member: Yes
Estimated Salary: $ 50000
So, should we say goodbye to that customer?

Solution:
"""

print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 77ms/step
[[False]]


In [17]:
"""
Therefore, this ANN model predicts that this customer stays in the bank!

Important note 1: Notice that the values of the features were all input in a double pair of square brackets. That's because 
the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of 
square brackets makes the input exactly a 2D array.

Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the 
first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we 
see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0".
"""

# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

63/63 [==============================] - 0s 629us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
[[1512   83]
 [ 188  217]]


0.8645